spring:
  datasource:
    url: jdbc:mysql://gondola.proxy.rlwy.net:54141/vivienda
    username: root
    password: uLTQukehcLkCFjnakhoBGXNKEhuxxUOL
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect  # evita el warning del Dialect si algo falla

server:
  port: 8080
